spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: epm_admin
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: http://localhost:8180/realms/epm/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.epm: DEBUG
