# WARNING: Replace all values before deploying to any non-local environment
apiVersion: v1
kind: Secret
metadata:
  name: epm-secrets
  namespace: epm
type: Opaque
data:
  POSTGRES_PASSWORD: Y2hhbmdlbWU=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  KEYCLOAK_CLIENT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  DEEPSEEK_API_KEY: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
