apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epm-ingress
  namespace: epm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: epm-api-gateway
                port:
                  number: 8080
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: epm-frontend
                port:
                  number: 80
