global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-auth:8081']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-user:8082']

  - job_name: 'project-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-project-service:8083']

  - job_name: 'task-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-task-service:8084']

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['epm-notification-service:8085']
