package com.epm.auth.domain.model;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

import com.epm.auth.domain.event.AccountRegisteredEvent;

/**
 * Account aggregate root.
 *
 * <p>Pure Java — no Spring, no JPA annotations.
 * State mutations happen only through business methods.
 * Domain events are accumulated and pulled by the application layer.
 *
 * <h2>Self-service signup / tenantId ownership</h2>
 * <p>This system uses a self-service signup model: every registration creates its
 * own tenant. The {@code tenantId} is generated <em>explicitly by the caller</em>
 * (the application use case) and passed into {@link #register}. It is NEVER generated
 * silently inside the aggregate factory. This makes the tenancy decision visible and
 * testable at the application boundary.
 *
 * <h2>firstName / lastName are transient</h2>
 * <p>The {@code accounts} table does not store first/last name columns. These fields
 * are held in memory only during the registration flow so that {@link #linkKeycloakUser}
 * can record an {@link AccountRegisteredEvent} with the full name data. They will be
 * {@code null} on any account reconstituted from the database.
 */
public class Account {

    private final UUID id;
    private final UUID tenantId;
    private UUID keycloakUserId;
    private final Email email;
    private AccountStatus status;
    private int failedAttempts;
    private Instant lastLoginAt;
    private final Instant createdAt;
    private Instant updatedAt;
    private int version;
    private Instant deletedAt;

    /**
     * Transient — not persisted. Held only during the registration flow so that
     * {@link #linkKeycloakUser} can include names in the domain event.
     * Always {@code null} on reconstituted accounts.
     */
    private final String firstName;

    /**
     * Transient — not persisted. See {@link #firstName}.
     */
    private final String lastName;

    private final List<Object> domainEvents = new ArrayList<>();

    private Account(
            UUID id,
            UUID tenantId,
            Email email,
            AccountStatus status,
            Instant createdAt,
            Instant updatedAt,
            String firstName,
            String lastName) {
        this.id = id;
        this.tenantId = tenantId;
        this.email = email;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.failedAttempts = 0;
        this.version = 0;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    /**
     * Factory method: creates a new account for self-service signup.
     *
     * <p>The {@code tenantId} is provided by the caller. In self-service signup,
     * the application layer generates a fresh tenant per registration using
     * {@code UUID.randomUUID()} (plain JDK — no framework dependency).
     *
     * <p>Only the account {@code id} is generated here. The {@link AccountRegisteredEvent}
     * is NOT recorded here because the {@code keycloakUserId} is not known yet.
     * Call {@link #linkKeycloakUser(UUID)} after the Keycloak user is created to set
     * the keycloakUserId and record the event with all fields populated.
     *
     * @param tenantId  tenant UUID — generated by the caller, one per self-service signup
     * @param email     raw email string (will be normalized)
     * @param firstName first name (transient — not persisted)
     * @param lastName  last name (transient — not persisted)
     * @return new Account without domain events (call linkKeycloakUser to record them)
     */
    public static Account register(UUID tenantId, String email, String firstName, String lastName) {
        UUID id = UUID.randomUUID();
        Instant now = Instant.now();
        Email normalizedEmail = new Email(email);
        return new Account(id, tenantId, normalizedEmail, AccountStatus.ACTIVE, now, now, firstName, lastName);
    }

    /**
     * Factory method: reconstitutes an Account from persistent storage.
     *
     * <p>Does NOT register domain events — this is a rehydration, not a new registration.
     * Used exclusively by the persistence adapter. firstName and lastName are {@code null}
     * because the accounts table does not store them.
     *
     * @param id             account UUID
     * @param tenantId       tenant UUID
     * @param keycloakUserId Keycloak user UUID (may be null)
     * @param email          normalized email string
     * @param status         account status
     * @param failedAttempts failed login attempts counter
     * @param lastLoginAt    last login timestamp (may be null)
     * @param createdAt      creation timestamp
     * @param updatedAt      last update timestamp
     * @param version        optimistic lock version
     * @param deletedAt      soft-delete timestamp (may be null)
     * @return reconstituted Account
     */
    public static Account reconstitute(
            UUID id,
            UUID tenantId,
            UUID keycloakUserId,
            String email,
            AccountStatus status,
            int failedAttempts,
            Instant lastLoginAt,
            Instant createdAt,
            Instant updatedAt,
            int version,
            Instant deletedAt) {
        Account account = new Account(id, tenantId, new Email(email), status, createdAt, updatedAt, null, null);
        account.keycloakUserId = keycloakUserId;
        account.failedAttempts = failedAttempts;
        account.lastLoginAt = lastLoginAt;
        account.version = version;
        account.deletedAt = deletedAt;
        return account;
    }

    /**
     * Links this account to its Keycloak user and records the {@link AccountRegisteredEvent}.
     *
     * <p>This method must be called exactly once, after the Keycloak user has been created
     * successfully. It sets the {@code keycloakUserId}, records the domain event (which now
     * carries the real Keycloak user ID), and updates {@code updatedAt}.
     *
     * @param keycloakUserId the Keycloak user UUID — must not be null
     * @throws IllegalArgumentException if {@code keycloakUserId} is null
     * @throws IllegalStateException    if this account is already linked to a Keycloak user
     */
    public void linkKeycloakUser(UUID keycloakUserId) {
        if (keycloakUserId == null) {
            throw new IllegalArgumentException("keycloakUserId must not be null");
        }
        if (this.keycloakUserId != null) {
            throw new IllegalStateException(
                    "Account " + id + " is already linked to Keycloak user " + this.keycloakUserId);
        }
        this.keycloakUserId = keycloakUserId;
        this.updatedAt = Instant.now();
        domainEvents.add(
                AccountRegisteredEvent.of(id, tenantId, email.value(), firstName, lastName, keycloakUserId));
    }

    /** Returns a copy of domain events and clears the internal list. */
    public List<Object> pullDomainEvents() {
        List<Object> events = Collections.unmodifiableList(new ArrayList<>(domainEvents));
        domainEvents.clear();
        return events;
    }

    // ── Getters ─────────────────────────────────────────────────────────────

    public UUID getId() {
        return id;
    }

    public UUID getTenantId() {
        return tenantId;
    }

    public UUID getKeycloakUserId() {
        return keycloakUserId;
    }

    public Email getEmail() {
        return email;
    }

    public AccountStatus getStatus() {
        return status;
    }

    public int getFailedAttempts() {
        return failedAttempts;
    }

    public Instant getLastLoginAt() {
        return lastLoginAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public int getVersion() {
        return version;
    }

    public Instant getDeletedAt() {
        return deletedAt;
    }

    /**
     * Returns the first name as supplied during registration.
     * {@code null} on reconstituted accounts (not persisted).
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Returns the last name as supplied during registration.
     * {@code null} on reconstituted accounts (not persisted).
     */
    public String getLastName() {
        return lastName;
    }
}
